### ISSUE TITLE
Erro ao gerar parcelas - cartão de crédito Pagbank

### ISSUE THREAD

**Issue by mateusrasteiro** [r-martins/PagBank-Magento1#26]
Olá Ricardo, tudo bem?

No checkout, ao preencher os dados do cartão no form do cartão de crédito do Pagbank, as parcelas não estão sendo geradas e o seguinte erro aparece no console:

![Screenshot from 2024-07-03 15-10-37](https://github.com/r-martins/PagBank-Magento1/assets/57551334/dfde25c1-4366-4413-8a77-450f8ef90946)

O cartão utilizado no teste é um cartão válido.
As demais formas de pagamento do módulo (PIX e Boleto) parecem estar funcionando corretamente.

O módulo está atualizado com os últimos commits na versão 4.4.0.
Loja Magento na versão 1.9.3.4
PHP 5.6

**Comment by r-martins** [comment]
PS: Conforme mencionado na resposta do chamado 20519 (5 Jul), não consegui reproduzir o problema na loja pois sequer consegui chegar ao checkout devido excesso de erros js.
Não obtive mais seu retorno desde então.

**Comment by mateusrasteiro** [comment]
Bom dia Ricardo, tudo bem?

Acabei conseguindo solucionar o erro por conta fazendo o seguinte ajuste:

[image: image.png]

Muito obrigado pela atenção e desculpe a demora para resposta.

Att,
Mateus Rasteiro.

Em ter., 13 de ago. de 2024 às 22:48, Ricardo Martins <
***@***.***> escreveu:

**Comment by r-martins** [comment]
Oi, @mateusrasteiro . Tudo bom?
A imagem não veio.
Pode mandar de novo ou [anexar direto no github](https://github.com/r-martins/PagBank-Magento1/issues/26)?

**Comment by mateusrasteiro** [comment]
Bom dia Ricardo,

Veja se consegue ver por esse link:
https://prnt.sc/GxePm4cpfryR

Att,
Mateus Rasteiro.

Em qui., 15 de ago. de 2024 às 03:43, Ricardo Martins <
***@***.***> escreveu:

**Comment by r-martins** [comment]
Obrigado por compartilhar.
Esse bug em especial foi corrigido na versão 4.4.2 como você pode ver [aqui](https://github.com/r-martins/PagBank-Magento1/commit/855de6c5c3ccba04ccb5ad3b13170cc47d8b5067).

**Comment by mateusrasteiro** [comment]
Bom dia Ricardo,

Que bom que já foi corrigido.

Vou ver de atualizar o módulo para pegar a correção.

Obrigado pela atenção.

Em sex., 16 de ago. de 2024 às 02:57, Ricardo Martins <
***@***.***> escreveu:
