### ISSUE TITLE
Erro após instalação: Uncaught Error: Call to undefined function str_contains()

### ISSUE THREAD

**Issue by tiagones** [r-martins/PagBank-Magento1#6]
Olá,

Ambiente da minha loja:
- Magento versão. 1.9.4.5
- php 7.2
O cache da loja foi limpo após a instalação, também desloguei e loguei no back-end após a instalação.

Segue o erro:

`Fatal error: Uncaught Error: Call to undefined function str_contains() in /home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Helper/Data.php:94 Stack trace: #0 /home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Helper/Data.php(30): RicardoMartins_PagBank_Helper_Data->isSandbox(NULL) #1 /home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Model/Observer.php(15): RicardoMartins_PagBank_Helper_Data->getPublicKeyEndpoint() #2 /home/tiago/sites/magento1/app/code/core/Mage/Core/Model/App.php(1374): RicardoMartins_PagBank_Model_Observer->generatePublicKey(Object(Varien_Event_Observer)) #3 /home/tiago/sites/magento1/app/code/core/Mage/Core/Model/App.php(1353): Mage_Core_Model_App->_callObserverMethod(Object(RicardoMartins_PagBank_Model_Observer), 'generatePublicK...', Object(Varien_Event_Observer)) #4 /home/tiago/sites/magento1/app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('admin_system_co...', Array) #5 /home/tiago/sites/magento1/app/c in /home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Helper/Data.php on line 94`

Este erro é apresentado no Back-end quando salvo quando inseri minha Chave Connect e salvando as configurações e também no Front-end logo após o início da renderização do Javascript:
`<script type="text/javascript">
    //<![CDATA[
    const preparePagBank = function(){
        if(typeof RMPagBankObj != "undefined"){
                        console.info('PagBank já inicializado.');
                        RMPagBankObj.addCardFieldsObserver();
            return;
        }
        let pagseguro_connect_3d_session = '<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function str_contains() in /home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Helper/Data.php:94
Stack trace:
#0 /home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Helper/Data.php(78): RicardoMartins_PagBank_Helper_Data-&gt;isSandbox(NULL)
#1 /home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Block/Form/Cc.php(78): RicardoMartins_PagBank_Helper_Data-&gt;get3DSecureSessionEndpoint()
#2 /home/tiago/sites/magento1/app/design/frontend/base/default/template/ricardomartins/pagbank/form/cc.phtml(105): RicardoMartins_PagBank_Block_Form_Cc-&gt;getPagSeguroConnect3dSession()
#3 /home/tiago/sites/magento1/app/code/core/Mage/Core/Block/Template.php(241): include('/home/tiago/sit...')
#4 /home/tiago/sites/magento1/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template-&gt;fetchView('frontend/base/d...')
#5 /home/tiago/sites/magento1/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Blo in <b>/home/tiago/sites/magento1/app/code/community/RicardoMartins/PagBank/Helper/Data.php</b> on line <b>94</b><br />
`

**Comment by r-martins** [comment]
Deixamos passar esse, @tiagones .
Já corrigi e vou lançar nos próximos minutos numa nova versão.
