### ISSUE TITLE
Erro ao realizar pedido usando outra forma de pagamento

### ISSUE THREAD

**Issue by tiagones** [r-martins/PagBank-Magento1#9]
Olá Ricardo,

Ao realizar um pedido escolhendo um método de pagamento diferente que não seja PagBank.

Erro:
`Fatal error: Uncaught Error: Call to a member function getPayment() on null in /home/tiago/sites/dhcp.magento1/app/code/community/RicardoMartins/PagBank/Block/Onepage/Success/Billet.php:10 Stack trace: #0 /home/tiago/sites/dhcp.magento1/app/design/frontend/base/default/template/ricardomartins/pagbank/checkout/info/billet.phtml(6): RicardoMartins_PagBank_Block_Onepage_Success_Billet->isVisible() #1 /home/tiago/sites/dhcp.magento1/app/code/core/Mage/Core/Block/Template.php(241): include('/home/tiago/sit...') #2 /home/tiago/sites/dhcp.magento1/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView() #3 /home/tiago/sites/dhcp.magento1/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView() #4 /home/tiago/sites/dhcp.magento1/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Template->_toHtml() #5 /home/tiago/sites/dhcp.magento1/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml() #6 /home/tiago/sites/dhcp.magento1/app/co in /home/tiago/sites/dhcp.magento1/app/code/community/RicardoMartins/PagBank/Block/Onepage/Success/Billet.php on line 10`

O pedido é registrado no Backend, porem o erro é apresentado na página de sucesso do pedido "https://dhcp.magento1.local/checkout/onepage/success/"

Ambiente da minha loja:
- Magento versão. 1.9.4.5
- php 7.2 (também testado no php 7.4)
- - Estou utilizando uma chave Sandbox (CONSANDBOX...)

**Comment by ligiasalzano** [comment]
Oi, @tiagones.
Obrigada por reportar.
Já encontramos o problema e estamos trabalhando nisso. Em breve publicaremos um novo release.
Te avisaremos aqui.

**Comment by r-martins** [comment]
Relacionado ao PR #10

**Comment by r-martins** [comment]
Fixed no [4.0.4](https://github.com/r-martins/PagBank-Magento1/releases/tag/4.0.4).
Valeu @tiagones
